name: Lint PR Title

permissions:
  contents: none

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Lint PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            fix
