name: Release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Run QA
        run: make qa
      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.7.1
      - name: Create new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git tag v${{ steps.get_next_version.outputs.version }}
          git push origin v${{ steps.get_next_version.outputs.version }}
      - name: Build artifacts
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          make build
      - name: Release new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          tag: v${{ steps.get_next_version.outputs.version }}
